import "./globals.css";
import QueryProvider from "@/components/provider/QueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
