import { Toaster } from "react-hot-toast";
import "./globals.css";
import QueryProvider from "@/components/provider/QueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <QueryProvider>
          {children}
          <Toaster position="top-center" containerClassName="z-[9999]" />
        </QueryProvider>
      </body>
    </html>
  );
}
